In [2]:
import numpy as np

In [4]:
## What does this command show you?
A = np.arange(10).reshape(2,5)
print(A)
type(A)

[[0 1 2 3 4]
 [5 6 7 8 9]]


numpy.ndarray

In [13]:
#a) Pick the elements 3 and 8
#Your code here!
A.shape
A[:, 3]

array([3, 8])

In [14]:
#n) Pick the elements 1, 2 and 3
# Your code here!
A[0, 1:4]

array([1, 2, 3])

In [15]:
B = np.arange(24).reshape(2,4,3)
print(B)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [24]:
#Pick the elements 1, 4 and 7
# Your code here
B[0, :3, 1]

array([1, 4, 7])

In [34]:
#Pick the elements 1, 2, 13 and 14
# Your code here
B[:,0:1,1:]

array([[[ 1,  2]],

       [[13, 14]]])

In [35]:
C = np.arange(12,36).reshape(3,2,4)
print(C)

[[[12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]]

 [[28 29 30 31]
  [32 33 34 35]]]


In [37]:
# Pick the elements 22 and 23
# Your code here
C[1, 0, 2:]

array([22, 23])

In [38]:
# Pick the elements 13, 14, 15, 21, 22, 23, 29, 30 and 31
#your code here
C[:,0, 1:]

array([[13, 14, 15],
       [21, 22, 23],
       [29, 30, 31]])

In [47]:
C = np.random.randint(12, size = (2,2,3))
print(C)

[[[ 3  6  2]
  [ 7 11  2]]

 [[ 0  2  8]
  [11  5  0]]]


In [ ]:
#What does the code show? Does it change every time you run it?
# Try selecting the first rows (i.e. first in our terms, not Python terms) in both groups.
# Try selecting the last column in the second group.

In [48]:
print(C[:, 0, :])
print(C[1, 1, :])

[[3 6 2]
 [0 2 8]]
[11  5  0]
